services:
  mongodb:
    image: mongo:latest
    container_name: qanda_mongodb
    environment:
      - MONGO_INITDB_DATABASE=qanda
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qanda_flask
    environment:
      - MONGO_URI=mongodb://mongodb:27017/qanda
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
      
volumes:
  mongo_data: